### ISSUE TITLE
Type '"metaExtensions"' cannot be used to index type 'ChartTypeRegistry[key]'

### ISSUE THREAD

**Issue by el** [chartjs/chartjs-chart-financial#112]
I think `metaExtensions: Record<string, never>;` should be added to the https://github.com/chartjs/chartjs-chart-financial/blob/f26e76e31af14ea6757b6ca57f8d847273284f7a/types/index.d.ts#L25 

Here is how a different package solved the same issue:
https://github.com/sgratzl/chartjs-chart-boxplot/issues/11
https://github.com/sgratzl/chartjs-chart-boxplot/blob/2fdbbdfa607a98c090c2e7a18dbf6e7438191627/src/controllers/BoxPlotController.ts#L74

**Comment by DaveSkender** [comment]
This might only need to be `metaExtensions: {};` to be comparable to [chart.js base types](https://github.com/chartjs/Chart.js/blob/4a9f446ff5c2c717dd28eb2a041aa55c2e66524d/types/index.esm.d.ts#L3463-L3470)

```typescript
  bar: {
    chartOptions: BarControllerChartOptions;
    datasetOptions: BarControllerDatasetOptions;
    defaultDataPoint: number;
    metaExtensions: {};
    parsedDataType: BarParsedData,
    scales: keyof CartesianScaleTypeRegistry;
  };
```
