### ISSUE TITLE
Candle border options

### ISSUE THREAD

**Issue by DaveSkender** [chartjs/chartjs-chart-financial#114]
Enhancement recommendation: on a chart with many candles, I would like the red and green colors to be prevalent.  With excess bars, the colors completely disappear.  Recommend either 1) have border options, or 2) default to borderless candles where wicks, border, and body are one color.

Current:
![4A57A580-7C16-4828-9CDB-9FDB26FB3D69](https://user-images.githubusercontent.com/8432125/145752700-49c20ff8-0079-43e7-8643-8db02c762111.jpeg)

Preferred:
![37ECC201-E02B-4615-AACF-261228B16EC8](https://user-images.githubusercontent.com/8432125/145752739-f8b3c8a9-1071-4f86-ae57-25b1352da718.jpeg)

**Comment by camheras** [comment]
You can already do something like that 😅

```
var defaultOpts = Chart.defaults.elements["candlestick"];
var chart = new Chart(ctx, {
	type: 'candlestick',
	data: {
		datasets: [{
			label: 'CHRT - Chart.js Corporation',
			data: barData,
			borderColor :{
				up: defaultOpts.color.up,
				down: defaultOpts.color.down,
				unchanged: defaultOpts.color.up
			}
		}]
	}})
```
<img width="1014" alt="Screenshot 2021-12-13 at 10 24 16" src="https://user-images.githubusercontent.com/26549675/145785769-e195832c-4387-4817-b6de-e1d37c8aa240.png">

**Comment by DaveSkender** [comment]
This probably works fine in straight JS, but I think it's choking on the custom candlestick element type in my Angular/Typescript setup.

```typescript
var defaultOpts = Chart.defaults.elements["candlestick"];

myConfig.data = {
  datasets: [
    {
      type: 'candlestick',
      label: 'Price',
      data: price,
      borderColor: {
        up: defaultOpts.color.up,
        down: defaultOpts.color.down,
        unchanged: defaultOpts.color.up
      },
      yAxisID: 'yAxis',
      order: 1
    },
    {
      type: 'bar',
      label: 'Volume',
      data: volume,
      yAxisID: 'volumeAxis',
      backgroundColor: 'lightblue',
      order: 99
    }
  ]
};
```

```error
 node_modules/chart.js/types/index.esm.d.ts:1653:3
    1653   borderColor: Color;
           ~~~~~~~~~~~
The expected type comes from property 'borderColor' which is declared here on 
type 'ChartDataset<keyof ChartTypeRegistry, 
(number | ScatterDataPoint | BubbleDataPoint | FinancialDataPoint)[]>' 
```

**Comment by DaveSkender** [comment]
This PR fixes my typings errors, but please do only treat a suggestion.
I'm not a JS pro, so there may be a more elegant way to handle it.

**Comment by DaveSkender** [comment]
WORKAROUND: for anyone using TypeScript, here's how I solved it:

```typescript
// add new dataset options type for borderColor
type CandlestickDatasetOptions = BarControllerDatasetOptions & {
    borderColor: {
        up: string,
        down: string,
        unchanged: string
    };
}
```

```typescript
// custom border colors
const candleOptions = Chart.defaults.elements["candlestick"];

// sets body color defaults
candleOptions.color.up = 'darkGreen';
candleOptions.color.down = 'darkRed';
candleOptions.color.unchanged = '#555555';

// define border and wicks color
// this should set the default, but still have to reapply in dataset (below)
candleOptions.borderColor = {
  up: candleOptions.color.up,
  down: candleOptions.color.down,
  unchanged: candleOptions.color.unchanged
};

// define base datasets
chartConfig.data = {
  datasets: [
    {
      type: 'candlestick',
      label: 'Price',
      data: price,
      yAxisID: 'yAxis',
      borderColor: candleOptions.borderColor // sets border and wicks color
    }
  ]
};
```
![image](https://user-images.githubusercontent.com/8432125/147795935-566e6f2d-d085-4ff9-bb01-db4c330889c2.png)

See PR (#115) for my suggestion on how to fix and use this in the main package.
