### ISSUE TITLE
[BUG] Border disappears after hover on candlestick

### ISSUE THREAD

**Issue by loicbourgois** [chartjs/chartjs-chart-financial#24]
On a candlestick chart, after hovering over a value, the borders disappear if the chart is configured to display a tooltip with the following parameters :

```
options: {
  tooltips: {
    position: 'nearest',
    mode: 'index',
  },
},
```
[jsfiddle](https://jsfiddle.net/loicbourgois/bhmtyn59/)

### Before hover

![image](https://user-images.githubusercontent.com/11260832/35440860-2ccf347c-0299-11e8-99a9-62ab3c7ef17c.png)

### After

![image](https://user-images.githubusercontent.com/11260832/35440876-43c3bf40-0299-11e8-9d00-76dde1a1812d.png)

**Comment by benmccann** [comment]
@loicbourgois thanks for reporting. This didn't use to happen before your commit to add OHLC support. You can verify by going back to the commit before that with `git reset --hard bc161d0ed61f92dc72d90684ba77ca6b3e91e09e`. Would you be able to look into this issue?

**Comment by loicbourgois** [comment]
Yes, I'm on it.

And actually, I think the problem has to do with the `borderColor` option in `datasets`.

See updated [jsfiddle](https://jsfiddle.net/bhmtyn59/2/).

**Comment by loicbourgois** [comment]
I added `console.log(vm.borderColor, globalOpts.elements.candlestick.borderColor);` in [Chart.elements.Candlestick.draw()](https://github.com/loicbourgois/chartjs-chart-financial/blob/border/src/element.candlestick.js#L17).
Used this code in a new [jsfiddle](https://jsfiddle.net/bhmtyn59/4/)

If `borderColor` is set, I have the following behavior for `console.log()` : 
* before hover : `#000 rgba(90, 90, 90, 1)`
* during hover : `rgb(0, 0, 0) rgba(90, 90, 90, 1)`
* after hover : `#000 rgba(90, 90, 90, 1)`

If `borderColor` is undefined, I have the following behavior for `console.log()` : 
* before hover : `undefined "rgba(90, 90, 90, 1)"`
* during hover : `rgba(0, 0, 0, 0.1) rgba(90, 90, 90, 1)`
* after hover : `rgba(0,0,0,0.1) rgba(90, 90, 90, 1)`

Also, I ran some grep commands :
```
$ grep -rnw ~/chartjs-chart-financial/src/ -e 'rgba(0, 0, 0, 0.1)'
no result
$ grep -rnw ~/chartjs-chart-financial/src/ -e 'rgba(0,0,0,0.1)'
no result
$ grep -rnw ~/Chart.js/src/ -e 'rgba(0, 0, 0, 0.1)'
~/Chart.js/src/scales/scale.radialLinear.js:20:			color: 'rgba(0, 0, 0, 0.1)',
~/Chart.js/src/core/core.scale.js:16:		color: 'rgba(0, 0, 0, 0.1)',
$ grep -rnw ~/Chart.js/src/ -e 'rgba(0,0,0,0.1)'
~/Chart.js/src/core/core.js:17:	defaultColor: 'rgba(0,0,0,0.1)',
```

So from what I understand, there is some code in a function related to hovering in Chart.js that checks if `vm.borderColor` is defined, and if it's not the case it affects a default value.

@benmccann Is this a bug in Chart.js or should this be resolved in financial ? 

Also, I find it strange that while hovering, the value is changed from `#000` to `rgb(0, 0, 0)`
Finally, there is some inconsistency with the colors : `rgba(0, 0, 0, 0.1)` vs `rgba(0,0,0,0.1)`. Does this justify a pull request ?

**Comment by benmccann** [comment]
This sounds like a bug in Chart.js. I'd recommend seeing if you can reproduce it with a plain bar chart or scatter chart to verify that and filing an issue upstream at https://github.com/chartjs/Chart.js/issues

**Comment by loicbourgois** [comment]
Found a way to fix the issue in Chart.js https://github.com/loicbourgois/Chart.js/commit/ea150cd8ef55ea8f35be7bb69c75296bb37f8d28 (but if feels like a hack)
[jsfiddle](https://jsfiddle.net/86rnxdrb/1/)
Will submit a PR in Chart.js

**Comment by benmccann** [comment]
This will be fixed in the next release of Chart.js https://github.com/chartjs/Chart.js/pull/5570

Thanks @loicbourgois for discovering the issue and driving the fix!

**Comment by benmccann** [comment]
This is fixed now. Thanks @loicbourgois for the report and all the help towards getting it fixed
