### ISSUE TITLE
npm install returning error `is not in the npm registry.`?

### ISSUE THREAD

**Issue by iTechKnow** [chartjs/chartjs-chart-financial#26]
I cant install this package, I did `npm install chartjs-chart-financial --save`  and it returned an error 
`npm ERR! 404  'chartjs-chart-financial' is not in the npm registry.`

**Comment by loicbourgois** [comment]
From the [README](https://github.com/chartjs/chartjs-chart-financial/blob/master/README.md#usage-and-roadmap)
>This module has not yet had its initial release and is not yet available on npm

For now,  you can build it from source or use the latest [Chart.Financial.js](https://github.com/chartjs/chartjs-chart-financial/blob/master/docs/Chart.Financial.js) available in [/docs](https://github.com/chartjs/chartjs-chart-financial/tree/master/docs)
