### ISSUE TITLE
How do I change the display of time?

### ISSUE THREAD

**Issue by rashearth** [chartjs/chartjs-chart-financial#31]
Hello.

Now, I am making a candlestick chart by using the data  below .
{ t: 'April 01 2018', o: 70.87, h: 80.13, l: 40.94, c: 50.24 },
				
The problem is that the x axis doesn't display as  "April 01" it says "12:00.00.000am".
Could you please help me how I can fix the time to "April 01"?

**Comment by rashearth** [comment]
Okay, I fixed this by simply adding the options as below.

 scales: {
					xAxes: [{
						
						type: 'time',
						display:true,
						time: {
							minUnit:'day',
						},
						scaleLabel: {
							display: true,
							labelString: 'Date'
						}
					}],
            
        },

**Comment by prachi96** [comment]
This worked. Thank you so much.
@rashearth
