### ISSUE TITLE
Configurations available for candlestick graph

### ISSUE THREAD

**Issue by prachi96** [chartjs/chartjs-chart-financial#39]
I was trying to format the value for xAxes using ticks callback but seems like not all chart configurations available in chart.js are available for this plugin.

**Comment by benmccann** [comment]
We just use the `time` scale that's available from Chart.js on the x-axis. It should be exactly the same

We do use a slightly different y-axis for the time being

**Comment by Griffork** [comment]
You can use the 'category' scale as well which allows you to provide your own data names.
