### ISSUE TITLE
First (left) and last (right) candle are truncated, draw outside   

### ISSUE THREAD

**Issue by sgornick** [chartjs/chartjs-chart-financial#42]
The candlestick chart doesn't render the first and last candle well.   It centers the candlestick but only draws the part of the candle that fits inside the chart.   

Using the sample ( https://www.chartjs.org/chartjs-chart-financial/ ) the April 1st candle only shows from the center of the candle and to the right (cutting off the left side).   The Jun 22nd candle only shows from the center of the candle and to the left (cutting off the right side).

Shouldn't there be a whitespace border to allow the full candle to be rendered?

**Comment by Griffork** [comment]
If you're using the category scale then you can set offset to true in the scale's options to get the outsides rendering. Don't know if this works with the time scale.
![example code](https://user-images.githubusercontent.com/3665998/44944302-a7f2fb00-ae17-11e8-9864-7701178daea7.png)

**Comment by amirderakh** [comment]
I'm struggling with this issue, too.
I guess most people use "type: 'time', distribution: 'series',". If you add "offset: true" here, a seemingly random amount off space is added to the left and right. Sometimes one candle, sometimes 2, sometimes 5.

It's important that the offset option works properly and always only adds space for half a candle to the left and right.

**Comment by benmccann** [comment]
I've updated the chart to set `offset: true` by default which addresses this issue. https://github.com/chartjs/chartjs-chart-financial/commit/333404af31aaaf03936ae20191bd92850b6d4680

@amirderakh I haven't seen the issue you're describing with `offset: true`. If anyone encounters that please open a new issue with a way to reproduce and I will take a look at it
