### ISSUE TITLE
Can't change border color

### ISSUE THREAD

**Issue by Asarael** [chartjs/chartjs-chart-financial#45]
Hi, I have been trying to apply the border color [enhancement](https://github.com/chartjs/chartjs-chart-financial/pull/37) but isn't not shown in the graph. Is necessary extra configuration?
![tempsnip](https://user-images.githubusercontent.com/39494179/46897183-dae0d380-ce46-11e8-873c-67592c9a0bfd.png)

**Comment by benmccann** [comment]
I just cut a new release which contains this enhancement. Can you try again?
https://github.com/chartjs/chartjs-chart-financial/commit/b4d9834eca5e04945673ab3c3bf1d0cd1ee3e294

**Comment by Asarael** [comment]
> I just cut a new release which contains this enhancement. Can you try again?
> [b4d9834](https://github.com/chartjs/chartjs-chart-financial/commit/b4d9834eca5e04945673ab3c3bf1d0cd1ee3e294)
