### ISSUE TITLE
Tooltip positioning not working correctly

### ISSUE THREAD

**Issue by AbelHeinsbroek** [chartjs/chartjs-chart-financial#49]
When using the 'average' position option the tooltips are not showing, when using {intersect: false, mode: 'index', position: 'nearest'} the tooltips show at the position of the cursor.

**Comment by benmccann** [comment]
This was just fixed in https://github.com/chartjs/chartjs-chart-financial/commit/d5ed737910f30bf2bd5ad94b603656e98fe0fbcf. If you sync from master and build a new version it should work

**Comment by benmccann** [comment]
Let me know if you still have problems after the fix
