### ISSUE TITLE
financial chart+ zoom not working out well

### ISSUE THREAD

**Issue by rashearth** [chartjs/chartjs-chart-financial#50]
Hi
i noticed that the zoom and financial chart is not really interacting right.
i am trying to zoom the candlestick chart as below,
![2019-02-16 0 05 43](https://user-images.githubusercontent.com/26535295/52865009-e0e11b00-317e-11e9-97bc-82de208b8505.png)

but the zoomed chart looks like this, and the candlestick is getting zoomed as well.
IS there any way i could process this out??
![2019-02-16 0 05 39](https://user-images.githubusercontent.com/26535295/52865024-e474a200-317e-11e9-9a00-2cecffde96cd.png)

**Comment by benmccann** [comment]
@rashearth we've made tons of fixes to the zoom plugin, which previously was rather buggy I'm afraid. Can you try again with 0.7.0 of the zoom plugin and let me know if it's still an issue?

**Comment by rashearth** [comment]
thx, its working out good now!

**Comment by RobCzikkel** [comment]
@rashearth 
Hey, sorry to bother you with this but this is the only post I found where someone managed to get this thing working.

Could you please have a look at my issue:
#https://github.com/chartjs/chartjs-plugin-zoom/issues/387#issue-710446984

I can't seem to get zoom working at all with time adapters, works with simple line charts tho.

Thanks a mill
