### ISSUE TITLE
tooltip for mixed chart (scatter + financial) not displaying correctly

### ISSUE THREAD

**Issue by rashearth** [chartjs/chartjs-chart-financial#54]
Hi, thx again for the wonderful app!
the mixed chart for financial and other bar or scatter implementing seems good!
but there is one issue for tooltip displaying.

Whenever i try to display the tooltip, it looks fine for barchart+ financial chart,
<img width="315" alt="スクリーンショット 2019-07-06 13 36 11" src="https://user-images.githubusercontent.com/26535295/60751638-c6a3be80-9ff3-11e9-8769-eb3f274d86c5.png">

but when i display it for financial chart+ scatter chart, the tooltip shows up far from the mouse hovering.as you could see in the screenshot, it moves on top of the y axis.

<img width="293" alt="スクリーンショット 2019-07-06 13 42 22" src="https://user-images.githubusercontent.com/26535295/60751651-0bc7f080-9ff4-11e9-8b2e-5b5ad021446c.png">

Could you kindly tell me if there any way to fix it?

Thank you,
Rasearth

**Comment by benmccann** [comment]
Thanks for the bug report @rashearth. Does this happen only with the financial chart or does it also happen if you use bar chart + scatter chart?

Chart.js 2.9.0 will introduce the concept of a floating bar chart. It'd also be interesting to test with the code from Chart.js master branch to see if it happens with a floating bar + scatter. A floating bar is very similar to a financial chart and I will update this library to have it be based on floating bars once 2.9.0 is released.

**Comment by rashearth** [comment]
Hi, thx for your quick help!
i found that it was my mistake.
i accidentally input the tooltip to the plugin section.
it turned out fine after i set into the right section.

will be looking forward for the new  floating chart function!!
