### ISSUE TITLE
Navigator

### ISSUE THREAD

**Issue by dastag** [chartjs/chartjs-chart-financial#65]
Is there any example of a chart with Navigator or is not implemented yet?

I was looking something like [this](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/navigator/margin/)

Thanks!

**Comment by benmccann** [comment]
No, nothing like that. You could try using it with the [zoom plugin](https://github.com/chartjs/chartjs-plugin-zoom) if you just want zooming, but that doesn't offer a "Navigator"
