### ISSUE TITLE
chart.js 3.0 migration

### ISSUE THREAD

**Issue by rashearth** [chartjs/chartjs-chart-financial#69]
Hi, one thing to tell, this is not an issue.

Its very great to hear that the chart.js 3.0 alpha have came out!
As i looked close, it was very nice, one of the best chart script i have seen before!

I know that financial is also working it out, but its highly appreciate for the migration to financial charts too.
Many people will be looking forward :) 
If there is any plan or schedule  for financial alpha ver, its very great to hear!

Thank you & Regards,
Rashearth

**Comment by benmccann** [comment]
Done. It now uses 3.0.0-alpha
