### ISSUE TITLE
Example with real data

### ISSUE THREAD

**Issue by sagive** [chartjs/chartjs-chart-financial#73]
I can't really find a real-life example - not some random auto-generated code.

an example with data from an API or arrays of data... got something anywhere? I mean just dropping the code - is it a private project? 

I see people asking and probably using this lib but how? where are some real-life examples? what am I missing...

**Comment by benmccann** [comment]
Sorry, but I don't have time to offer support, so instructions on loading data are outside the scope of this project

**Comment by sagive** [comment]
Asking for better instructions / examples isn't like asking for support man.
