### ISSUE TITLE
How to fit data values in X axis

### ISSUE THREAD

**Issue by Osolemio44** [chartjs/chartjs-chart-financial#82]
How can i create a [line chart](https://www.chartjs.org/docs/latest/charts/line.html) with 8000 data values and fit them in my X axis with 5 labels. It should look something like this: 
![1](https://user-images.githubusercontent.com/55595063/92707316-793c8300-f355-11ea-8612-996fc9ede3b0.png)
I dont want to create 8000 labels for the 8000 data values.

**Comment by benmccann** [comment]
This library is for stock charts only - not line charts

**Comment by Osolemio44** [comment]
i have no idea what you are talking about.  then what is that :  https://www.chartjs.org/docs/latest/charts/line.html
