### ISSUE TITLE
mixed types

### ISSUE THREAD

**Issue by erikjonkers** [chartjs/chartjs-chart-financial#96]
Hi,

I try to use mixed types:
https://www.chartjs.org/docs/latest/charts/mixed.html

But the 'type' value is dominant at a higher level;

```
var chart = new Chart(ctx, {
        type: "candlestick",
        data: {
            datasets: [{
                type: "candlestick",
                label: marketName,
                data: candleData
            }, {
                type: "line",
                label: supportLevel,
                data: lineData
            }
        }
    }
);
```

**Comment by CupcakeThief** [comment]
Looks fine to me, but could do with some coverage for this in the demo page.
(working with chartjs 3.2.1)

![image](https://user-images.githubusercontent.com/495563/119180898-ce926d80-ba68-11eb-8781-9a89602a01d9.png)

**Comment by Daanra** [comment]
@CupcakeThief 

Would you mind sharing your code? I'm also unable to get mixed types working.

**Comment by CupcakeThief** [comment]
Can't do that, as it's all in C#/Blazor, would be more confusing than helpful.

Instead I've twiddled the sample page, see pull request #97 which adds a line for close prices.

**Comment by CupcakeThief** [comment]
I've fixed tooltip labeling for mixed charts, under the same PR.

**Comment by CupcakeThief** [comment]
NB there's quite a big gotcha with financial plugin; parsing for datetime values is disabled by default, for performance.
Make sure you convert x values to epoch timestamps, e.g. as per demo page
```
x: luxon.DateTime.fromRFC2822(dateStr)
```

**Comment by benmccann** [comment]
fixed by https://github.com/chartjs/chartjs-chart-financial/pull/97
